#pragma once
#include "tests/000.bugs.h"
#include "tests/001.componentAndProperties.h"
#include "tests/002.componentLink.h"
#include "tests/003.componentAsParameter.h"
#include "tests/004.functionCall.h"
#include "tests/005.dataArray.h"
#include "tests/006.dataStruct.h"
#include "tests/007.complexData.h"
#include "tests/008.objectArray.h"
#include "tests/013.references.h"
#include "tests/014.componentByType.h"
#include "tests/015.nestedObject.h"
#include "tests/016.lambda.h"
#include "tests/018.subTreeObjects/018.subTreeObjects.h"
#include "tests/019.crossReference.h"
#include "tests/020.circlePoints.h"
#include "tests/011.spawner.h"
#include "tests/021.staticTypization.h"
#include "tests/022.componentsReordering.h"
#include "tests/023.noNamedComponents.h"
#include "tests/024.noNamedInstance.h"
#include "tests/025.nestedSpawners.h"
#include "tests/026.cyclicSpawners.h"
#include "tests/027.configurableSpawners.h"
#include "tests/028.expressionsConversion.h"
#include "tests/029.external.h"
#include "tests/030.mixedInstanceAndComponents.h"
#include "tests/031.nestedObjectsInitialized.h"
#include "tests/032.spawnerPrototypeInternalLinks.h"
#include "tests/008.1.objectArrayEmbeddedScopename.h"
#include "tests/utils.h"

#include "bugs/bug0005.h"
#include "bugs/bug0006.h"
#include "bugs/bug0008.h"


#ifdef DEFINE_SDK_LIB
#pragma DEFINE_SDK_LIB(componentModelTesting)
#endif