#pragma once

#include <math.h>
#include "vector.h"

namespace Geometry
{
	VECTOR1_COMPONENT_TYPE(POS1, POSITION, float, 0.01f);
	VECTOR2_COMPONENT_TYPE(POS2, POSITION, float, 0.01f);
	VECTOR3_COMPONENT_TYPE(POS3, POSITION, float, 0.01f);
	VECTOR4_COMPONENT_TYPE(POS4, POSITION, float, 0.01f);
	VECTOR4_COMPONENT_TYPE(POST, POSITIONT, float, 0.01f);

// 	VECTOR2_COMPONENT_TYPE(POS2_HALF, half_float);
// 	VECTOR4_COMPONENT_TYPE(POS4_HALF, half_float);
// 	VECTOR4_COMPONENT_TYPE(POST_HALF, half_float);
}